vim.g.python3_host_prog = "/usr/bin/python"

require("utils")
require("settings")
require("plugins")
require("globals")
require("lsp")
require("keymappings")
require("colorscheme")
require("nvim-galaxyline")

-- Plugins
require("autocmds")
require("nvim-compe")
require("autopairs")
require("treesitter")
require("nvim-bufferline")
require("nvim-telescope")
require("nvim-comment")
require("nvim-colorizer")
require("nvim-gitsigns")
-- require('nvim-FTerm')
require("nvim-nvimtree")

-- LSP
require("lsp.lua-lsp")
-- require('lsp.python-ls')
-- require('lsp.bash-ls')
-- require('lsp.html-ls')
-- require('lsp.json-ls')
-- require('lsp.php-ls')
-- require('lsp.vim-ls')
-- require('lsp.css-ls')
-- require('lsp.js-ts-ls')
-- require('lsp.yaml-ls')
-- require('lsp.efm-general-ls')
