vim.o.autoindent=true
vim.o.autoread=true
vim.o.autowrite=true
vim.o.background="dark"
vim.o.backup = false
vim.o.clipboard="unnamedplus"
vim.o.cmdheight=2
vim.wo.cursorline=true
vim.o.diffopt="vertical"
vim.o.encoding="utf-8"
vim.bo.expandtab= true
vim.o.hidden=true
vim.o.ignorecase=true
vim.o.incsearch=true
vim.o.mouse="a"
vim.wo.number=true
vim.wo.relativenumber=true
vim.o.swapfile=false
vim.o.scrolloff=7
vim.o.shiftwidth=4
vim.o.showcmd=true
vim.o.showmatch=true
-- vim.o.shortmess="c"
vim.o.sidescroll=5
vim.wo.signcolumn = "yes"
vim.o.smartcase=true
vim.o.smarttab=true
vim.o.spell=true
vim.o.splitright=true
vim.o.softtabstop=4
vim.o.tabstop=4
vim.o.termguicolors=true
vim.o.undofile=true
vim.o.updatetime=150
vim.wo.wrap=false
vim.o.writebackup=false
